### ISSUE TITLE
Category buttons not responding as expected

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#1]
https://d.pr/RmnTLa

**Comment by d4mation** [comment]
Seems to only happen when you click _on the text_ as it appears on top of the link itself.

`pointer-events: none;` on the `<p>` tag for the text corrects this.

**Comment by BigActual** [comment]
Good point, true. Yes, clicking on the hexagon does do the job. I guess we need an additional set of links attached to the text itself.
