### ISSUE TITLE
Image Optimization

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#16]
Optimize images
Images
Fail (0%)
Optimize the following images to reduce their size by 159.5KiB (13% reduction).

Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/02/Boodstore.jpg could save 29.6KiB (26% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/02/HoneyDip.jpg could save 22.7KiB (6% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/01/BK140a-300x300.jpg could save 18.6KiB (59% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/04/BK674-2-300x300.jpg could save 17.8KiB (59% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/04/BK792-2-300x300.jpg could save 16.6KiB (64% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/04/BK845-3-300x300.jpg could save 12.8KiB (61% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/01/primary-logo.png could save 11.2KiB (51% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/02/Gardening4.jpg could save 8.6KiB (2% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/themes/napoleonbeesupply-theme-2017/dist/assets/images/background-honey.jpg could save 8.2KiB (45% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/themes/napoleonbeesupply-theme-2017/dist/assets/images/honeycomb-overlay-2.png could save 4.7KiB (53% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/themes/napoleonbeesupply-theme-2017/dist/assets/images/honeycomb-overlay-1.png could save 3.8KiB (51% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/uploads/2018/04/charlotte-hiving-bees.jpg could save 2.6KiB (4% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/themes/napoleonbeesupply-theme-2017/dist/assets/images/off-canvas-background.jpg could save 1.3KiB (22% reduction). .
Losslessly compressing https://napoleonbeesupply.com/wp-content/themes/napoleonbeesupply-theme-2017/dist/assets/images/rbm-logo-footer.png could save 1.1KiB (38% reduction). .

**Comment by d4mation** [comment]
We could use an application like EWWW to run through all images on the site to optimize them. The majority of these are from the `/wp-uploads/` directory which means they were uploaded to the User/are attached to a Post on the site.

Some of the others are from within the Theme Directory and we could look at scripts to automatically optimize those locally. FoundationPress includes that and the Theme _should_ be using it, but it may not be for some reason or another or it could not be optimizing as much as the Page Speed test results are wanting.

**Comment by BigActual** [comment]
CDN initialized on WP Engine

**Comment by BigActual** [comment]
Object Cache enabled

**Comment by d4mation** [comment]
The images within the Theme directory have been optimized as part of #17 and #18

**Comment by joelyoder** [comment]
The images have all been optimized. The biggest issue was some images in the honeycomb section that were being loaded full size. This issue was fixed earlier in the summer, so I'm closing this ticket.
