### ISSUE TITLE
Enable Compression

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#19]
Enable compression for the following resources to reduce their transfer size by 111.5KiB (73% reduction).

Compressing https://cdn.rlets.com/capture_static/mms/capture.js could save 105.9KiB (74% reduction).
Compressing https://cde482ff-0904-4b55-b0d8-33b1f481a5c3.rlets.com/static/storage.html could save 4.5KiB (57% reduction).
Compressing https://pixel.mathtag.com/event/js?mt_id=1192822&mt_adid=142432&mt_exem=&mt_excl=&v1=&v2=&v3=&s1=&s2=&s3=&mm_bnc&mm_bct could save 901B (57% reduction).
Compressing https://www.jccmi.edu/wp-content/plugins/gravity-forms-wcag-20-form-fields/js/gf_wcag20_form_fields.min.js?ver=5.1.1 could save 248B (45% reduction

**Comment by d4mation** [comment]
>  https://www.jccmi.edu/

Did this end up in the wrong repo?
