### ISSUE TITLE
Leverage Browser Caching

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#20]
Leverage browser caching for the following cacheable resources:

https://capture-api.reachlocalservices.com/originCountry (expiration not specified)
https://cdn.rlets.com/capture_configs/cde/482/ff0/9044b55b0d833b1f481a5c3.js (expiration not specified)
https://cdn.rlets.com/capture_static/mms/capture.js (expiration not specified)
https://load77.exelator.com/pixel.gif (expiration not specified)
https://www.googletagmanager.com/gtag/js?id=AW-855905882 (15 minutes)
https://www.googletagmanager.com/gtm.js?id=GTM-NR8RXL7 (15 minutes)
https://bat.bing.com/bat.js (30 minutes)
https://translate.googleapis.com/translate_static/css/translateelement.css (1 hour)
https://translate.googleapis.com/translate_static/js/element/main.js (1 hour)
https://www.googleadservices.com/pagead/conversion_async.js (1 hour)
https://js-agent.newrelic.com/nr-1118.min.js (2 hours)
https://www.google-analytics.com/analytics.js (2 hours)

**Comment by joelyoder** [comment]
The only scripts that are not using browser caching on NBS is Google Tag Manager, which not something that we can change (we discussed this at some length a few months back). This is not an issue that is dragging down our perf according to Lighthouse, so I think this is safe to close.
