### ISSUE TITLE
Avoid Bad Requests

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#21]
The following requests are returning 404/410 responses. Either fix the broken links or remove the references to the non-existent resources.

https://fault.rlets.com/_.gif?s=cde482ff-0904-4b55-b0d8-33b1f481a5c3&m=Unknown%20OS%20or%20OS%20Version&f=Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64%3B%20rv%3A54.0)%20Gecko%2F20100101%20Firefox%2F54.0
https://www.jccmi.edu/wp-content/plugins/gravity-forms-sticky-list/css/sticky-list_styles.css?ver=5.1.1
https://www.jccmi.edu/wp-content/plugins/gravity-forms-sticky-list/js/sticky-list_responsive.js?ver=5.1.1

**Comment by joelyoder** [comment]
The links above were issues with the Jackson College site. I've checked NBS and we do not have any bad requests, so I'm closing this ticket.
