### ISSUE TITLE
Defer Parsing of JavaScript

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#22]
145.3KiB of JavaScript is parsed during initial page load. Defer parsing JavaScript to reduce blocking of page rendering.

https://www.jccmi.edu/wp-includes/js/jquery/jquery.js?ver=1.12.4 (87.0KiB)
https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js?ver=1.8.0 (37.3KiB)
https://www.jccmi.edu/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (7.7KiB)
https://cde482ff-0904-4b55-b0d8-33b1f481a5c3.rlets.com/static/storage.html (5.7KiB of inline JavaScript)
https://www.jccmi.edu/ (4.0KiB of inline JavaScript)
https://www.jccmi.edu/wp-content/plugins/miniorange-saml-20-single-sign-on/includes/js/settings.js?ver=5.1.1 (2.2KiB)
https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit (1.1KiB)
https://www.jccmi.edu/wp-content/plugins/gravity-forms-sticky-list/js/sticky-list_responsive.js?ver=5.1.1 (162B)

**Comment by joelyoder** [comment]
The links in this ticket are for Jackson College, but the JS has been deferred on NBS, so this is good to close.
