### ISSUE TITLE
Minimize Redirects

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#23]
Remove the following redirect chain if possible:

https://uipus.semasio.net/mediamath/1/info?sType=sync&sExtCookieId=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&sInitiator=external
https://uipus.semasio.net/mediamath/1/info2?sType=sync&sExtCookieId=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&sInitiator=external
https://match.adsrvr.org/track/cmf/generic?ttd_pid=semasio&ttd_tpi=1
https://match.adsrvr.org/track/cmb/generic?ttd_pid=semasio&ttd_tpi=1
https://uipglob.semasio.net/tradedesk/1/info?sType=sync&gdpr=0&gdpr_consent=&sInitiator=internal&sExtCookieId=e53bf928-06c0-4274-94bc-57e023cea3b3
https://cm.g.doubleclick.net/pixel?google_nid=semasio_ddp&google_cm
https://uipglob.semasio.net/dbm/1/info?sType=sync&sExtCookieId=CAESEOUsLW7pCpDdUsLS39vRcxE&sInitiator=internal&google_cver=1&google_cver=1
https://cms.analytics.yahoo.com/cms?partner_id=SEMAS&gdpr=false&sInitiator=internal
https://uipus.semasio.net/oath/1/info?sType=sync&sExtCookieId=y-Af_IOHB1lwQyJKRu0yxa0Mkm56eQ7YCSUvI-&sInitiator=internal&gdpr=false
Remove the following redirect chain if possible:

https://pixel.tapad.com/idsync/ex/receive?partner_id=2989&partner_device_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://pixel.tapad.com/idsync/ex/receive/check?partner_id=2989&partner_device_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://match.adsrvr.org/track/cmf/generic?ttd_pid=tapad&ttd_tpi=1&ttd_puid=dab36fb0-6227-11e9-b170-0a580a4c0207%252C&gdpr=0&gdpr_consent=
https://match.adsrvr.org/track/cmb/generic?ttd_pid=tapad&ttd_tpi=1&ttd_puid=dab36fb0-6227-11e9-b170-0a580a4c0207%252C&gdpr=0&gdpr_consent=
https://pixel.tapad.com/idsync/ex/receive?partner_id=1830&partner_device_id=e53bf928-06c0-4274-94bc-57e023cea3b3&ttd_puid=dab36fb0-6227-11e9-b170-0a580a4c0207%2C
Remove the following redirect chain if possible:

https://cm.g.doubleclick.net/pixel?google_nid=mediamath&google_cm&google_hm=HxtcuPRSTACvQ21sZRtXww
https://cm.g.doubleclick.net/pixel?google_nid=mediamath&google_cm=&google_hm=HxtcuPRSTACvQ21sZRtXww&google_tc=
https://sync.mathtag.com/sync/img?mt_exid=4&mt_ec=64ws&mt_exuid=&google_gid=CAESEI-OinIaGCzc7Kv1MAK-Irs&google_cver=1
https://cm.g.doubleclick.net/pixel?google_nid=mediamath&google_hm=HxtcuPRSTACvQ21sZRtXww
Remove the following redirect chain if possible:

https://ib.adnxs.com/getuid?https://sync.mathtag.com/sync/img?mt_exid=13&mt_mminit=1&mt_exuid=$UID
https://ib.adnxs.com/bounce?%2Fgetuid%3Fhttps%3A%2F%2Fsync.mathtag.com%2Fsync%2Fimg%3Fmt_exid%3D13%26mt_mminit%3D1%26mt_exuid%3D%24UID
https://sync.mathtag.com/sync/img?mt_exid=13&mt_mminit=1&mt_exuid=2030225572156135544
Remove the following redirect chain if possible:

https://loadm.exelator.com/load/?p=204&g=101&buid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&j=0
https://loadm.exelator.com/load/?p=204&g=101&buid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&j=0&xl8blockcheck=1
https://load77.exelator.com/pixel.gif
Remove the following redirect chain if possible:

https://px.powerlinks.com/user/sync/dsps?userId=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&sourceId=aa4e7548-789b-4df8-a72f-d951a5b206eb
https://visitor.omnitagjs.com/visitor/sync?uid=2ee744dfd5d22deb53e66beaae5c8e16&visitor=cAynfPsi8FP7U30BxQFykSs-Va-EVslEd_rLrhddpNs%3D&name=POWERLINKS
https://visitor-usa02.omnitagjs.com/visitor/sync?name=POWERLINKS&uid=2ee744dfd5d22deb53e66beaae5c8e16&visitor=cAynfPsi8FP7U30BxQFykSs-Va-EVslEd_rLrhddpNs%3D
Remove the following redirect chain if possible:

https://x.bidswitch.net/sync?dsp_id=80&user_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&expires=30
https://x.bidswitch.net/ul_cb/sync?dsp_id=80&user_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&expires=30
https://player.mediabong.net/sync/bsw?uid=c33bdbbe-ce71-4509-b035-2642d50dee8a&custom_data=
Remove the following redirect chain if possible:

https://ad.360yield.com/match?publisher_dsp_id=5&external_user_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://ad.360yield.com/ul_cb/match?publisher_dsp_id=5&external_user_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
Remove the following redirect chain if possible:

https://cm.g.doubleclick.net/pixel?google_nid=mediamath_dmp&google_cm
https://pixel.mathtag.com/sync/img?mt_exid=10074&google_gid=CAESEOhxUN5dt4Jfp5Oh0Z-XDFM&google_cver=1
Remove the following redirect chain if possible:

https://dpm.demdex.net/ibs:dpid=269&dpuuid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://dpm.demdex.net/demconf.jpg?et:ibs%7cdata:dpid=269&dpuuid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
Remove the following redirect chain if possible:

https://dsum-sec.casalemedia.com/rum?cm_dsp_id=3&external_user_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://dsum-sec.casalemedia.com/rum?cm_dsp_id=3&external_user_id=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&C=1
Remove the following redirect chain if possible:

https://global.ib-ibi.com/image.sbxx?go=247256&pid=310&xid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://ib.mookie1.com/image.sbxx?go=247256&pid=310&xid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
Remove the following redirect chain if possible:

https://i.liadm.com/s/37464?bidder_id=7156&bidder_uuid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://i.liadm.com/s/37464?bidder_id=7156&bidder_uuid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&_li_chk=true&previous_uuid=0d96f7bfb59846e4b82cdae74b82f343
Remove the following redirect chain if possible:

https://pixel.advertising.com/ups/55938/sync?uid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&_origin=1
https://pixel.advertising.com/ups/55938/sync?uid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&_origin=1&verify=true
Remove the following redirect chain if possible:

https://pixel.mathtag.com/event/js?mt_id=1192822&mt_adid=142432&mt_exem=&mt_excl=&v1=&v2=&v3=&s1=&s2=&s3=
https://pixel.mathtag.com/event/js?mt_id=1192822&mt_adid=142432&mt_exem=&mt_excl=&v1=&v2=&v3=&s1=&s2=&s3=&mm_bnc&mm_bct
Remove the following redirect chain if possible:

https://pixel.rubiconproject.com/tap.php?v=4222&nid=1512&put=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&expires=28
https://pixel.rubiconproject.com/tap.php?cookie_redirect=1&v=4222&nid=1512&put=1f1b5cb8-f452-4c00-af43-6d6c651b57c3&expires=28
Remove the following redirect chain if possible:

https://sync.crwdcntrl.net/map/c=4735/tp=MDMA/tpid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://sync.crwdcntrl.net/map/ct=y/c=4735/tp=MDMA/tpid=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
Remove the following redirect chain if possible:

https://us-u.openx.net/w/1.0/sd?id=536872786&val=1f1b5cb8-f452-4c00-af43-6d6c651b57c3
https://us-u.openx.net/w/1.0/sd?cc=1&id=536872786&val=1f1b5cb8-f452-4c00-af43-6d6c651b57c3

**Comment by joelyoder** [comment]
This is not an issue on NBS. I believe these links above were probably related to Jackson College like the other issues in this repo, since NBS doesn't even use a number of these tracking services.
