### ISSUE TITLE
Refund buttons need styling fix

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#28]
The [Refund to PayPal] button, and the button next to it, in the product edit refund view, are showing as code instead of as actual buttons.
![image](https://user-images.githubusercontent.com/8271108/113448992-e2a3e200-93ca-11eb-94a8-82d451a38098.png)

**Comment by d4mation** [comment]
This seems to only happen once you've typed in an amount. Weird. 

If I had to guess, this is a WooCommerce bug, or potentially a bug with the PayPal integration. 

I'll see if I can find a way to fix this from our end, but either way we will probably need to report this to the developers of one of those two plugins.

**Comment by d4mation** [comment]
So, this kind of a WooCommerce bug, but also isn't. I need to look into this more, but it is likely a change that needs to be made to the PayPal plugin to correct this.

https://github.com/woocommerce/woocommerce/issues/29377#issuecomment-804144355

I'll see if this can be adjusted in the PayPal plugin to work as it expects.

**Comment by d4mation** [comment]
Ah, nope. This was our bad. There was some code in use on the Frontend that was adjusting this and we want to ensure it doesn't run on the backend. Fix incoming.
