### ISSUE TITLE
Adding the Blog Archive

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#3]
I have the first post loaded. How do you want to lay out the Blog Archive?

**Comment by joelworsham** [comment]
What do you mean "lay out"?

**Comment by BigActual** [comment]
I mean that in its current state, the blog archive is not displayed. Could you implement that, please? I don't remember if there is a layout for the blog archive, so I was wondering how you would like to do the design if it does not already exist.

**Comment by joelworsham** [comment]
Already setup, but no access was created. I just created the page napoleonbee.wpengine.com/blog/

If you want, we can add it as a primary link in the header.
