### ISSUE TITLE
Adding Events

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#4]
The first class needs to be loaded. Do you want to go with events calendar pro or an alternative?

**Comment by joelworsham** [comment]
I was not aware this website would have anything like this, so I haven't given it any thought.

I don't really care too much what we go with. Events Calender Pro is probably good.

**Comment by BigActual** [comment]
Yes, but they probably don't need the pro version. Just use standard: https://wordpress.org/plugins/the-events-calendar/
