### ISSUE TITLE
map with directions

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#5]
Ties in with #2. the map needs to be actionable. Some map programs have given end users bum directions so the one we use needs to be tested for accuracy and usability.

**Comment by joelworsham** [comment]
I don't understand what you want here. Directions? From where? I plan on just embedding a Google Map.

**Comment by BigActual** [comment]
The client wanted a map solution that allows the end user to request directions to their location, but they've had problems in the past with these taking people to the wrong place.

**Comment by BigActual** [comment]
https://wordpress.org/plugins/wp-google-maps/ may take care of the problem. There are probably better solutions but this is the one I saw first. It's well documented, so...

**Comment by joelworsham** [comment]
I'd highly advise not to encourage users to get directions from the website. It's best to just embed a simple Google Map and let the user do the rest. They can probably end up clicking it and being taken to Google Maps, where they can easily request directions.
