### ISSUE TITLE
Add Post to Social features 

### ISSUE THREAD

**Issue by BigActual** [realbig/napoleonbeesupply-theme-2017#7]
Kyle had us using a paid service. I'd like to try one of the better documented and updated free tools. Could you please install one of these, at your discretion:
https://wordpress.org/plugins/blog2social/ 
https://wordpress.org/plugins/social-media-auto-publish/

I plan on working with Marion on posting to social media on Wed. 5/23/18.

**Comment by joelworsham** [comment]
I've got it installed. It seems that you will need to go here: http://napoleonbeesupply.com/wp-admin/admin.php?page=blog2social-network and add the pages and accounts. You or Marion, whoever has the credentials.

I would think it should work after that.

**Comment by BigActual** [comment]
Sent request to Marion for configuration.
